# Generated by Django 3.1.3 on 2021-01-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='questions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
