# Generated by Django 3.1.3 on 2021-01-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210107_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
