# Generated by Django 3.1.3 on 2021-01-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210107_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='i',
        ),
    ]
